name: Run Scanner During Market Hours

on:
  schedule:
    - cron: '20 3-9 * * 1-5'
  workflow_dispatch:

jobs:
  run-scanner:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install requests pandas --no-cache-dir

      - name: Run script
        run: |
          python -u github_auto.py
